print(x)  # error 1
x=5
print(y)  # error 2
y= 5


break

def foo(arg1, arg1): # error 3
    return "hello!" # error 4
    return "hello!" # error 5